version: '3.4'

services:
  # frontend:
    # image: frontend
    # build:
    #   context: frontend
    #   dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    #   PORT:3000
    # ports:
    #   - 3000:3000
  emitter-limerick:
    image: emitter
    build:
      context: emitter
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      CLIENTID: Limerick
  emitter-cork:
    image: emitter
    build:
      context: emitter
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      CLIENTID: Cork
